syntax = "proto3";

package user.v1;

import "google/protobuf/timestamp.proto";

service UserService {
    rpc CreateUser(CreateUserRequest) returns (CreateUserResponse) {};
    rpc GetUserById(GetUserByIdRequest) returns (GetUserByIdResponse) {};
    rpc GetUserByEmail(GetUserByEmailRequest) returns (GetUserByEmailResponse) {};
    rpc UpdateUserData(UpdateUserDataRequest) returns (UpdateUserDataResponse) {};
    rpc DeleteUser(DeleteUserRequest) returns (DeleteUserResponse) {};
}

message User {
    string user_id = 1;
    string username = 2;
    string email = 3;
    string role = 4; 
    bool is_verified = 5;
    google.protobuf.Timestamp created_at = 6;
} 


message CreateUserRequest {
    string email = 1;
    string password = 2;
    string username = 3;
}
message CreateUserResponse {    
    User user = 1;
}


message GetUserByIdRequest {
    string user_id = 1;
}
message GetUserByIdResponse {
    User user = 1;
}


message GetUserByEmailRequest {
    string email = 1;
}
message GetUserByEmailResponse {
    User user = 1;
}


message UpdateUserDataRequest {
    string user_id = 1;
    optional string username = 2;
}
message UpdateUserDataResponse {
    User user = 1;
}


message DeleteUserRequest {
    string user_id = 1;
}
message DeleteUserResponse {
    string user_id = 1;
}