syntax = "proto3";

package auth.v1;

service PasswordService {
    rpc StorePassword(StorePasswordRequest) returns (StorePasswordResponse) {};
    rpc ConfirmPassword(ConfirmPasswordRequest) returns (ConfirmPasswordResponse) {};
    rpc ChangePassword(ChangePasswordRequest) returns (ChangePasswordResponse) {};
}

message StorePasswordRequest {
    string user_id = 1;
    string password = 2;
}
message StorePasswordResponse {
    bool is_stored = 1;
}


message ConfirmPasswordRequest {
    string email = 1;
    string password = 2;
}
message ConfirmPasswordResponse {
    bool is_valid = 1;
}


message ChangePasswordRequest {
    string user_id = 1;
    string old_password = 2;
    string new_password = 3;
}
message ChangePasswordResponse {
    bool is_changed = 1;
}