// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v7.35.1
// source: auth/v1/password_pb.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "auth.v1";

export interface StorePasswordRequest {
  userId: string;
  password: string;
}

export interface StorePasswordResponse {
  isStored: boolean;
}

export interface VerifyPasswordRequest {
  email: string;
  password: string;
}

export interface VerifyPasswordResponse {
  isValid: boolean;
}

export interface GetChangePasswordTokenRequest {
  userId: string;
}

export interface GetChangePasswordTokenResponse {
  token: string;
}

export interface ChangePasswordRequest {
  userId: string;
  token: string;
  oldPassword: string;
  newPassword: string;
}

export interface ChangePasswordResponse {
  isChanged: boolean;
}

export const AUTH_V1_PACKAGE_NAME = "auth.v1";

export interface PasswordServiceClient {
  storePassword(request: StorePasswordRequest): Observable<StorePasswordResponse>;

  verifyPassword(request: VerifyPasswordRequest): Observable<VerifyPasswordResponse>;

  getChangePasswordToken(request: GetChangePasswordTokenRequest): Observable<GetChangePasswordTokenResponse>;

  changePassword(request: ChangePasswordRequest): Observable<ChangePasswordResponse>;
}

export interface PasswordServiceController {
  storePassword(
    request: StorePasswordRequest,
  ): Promise<StorePasswordResponse> | Observable<StorePasswordResponse> | StorePasswordResponse;

  verifyPassword(
    request: VerifyPasswordRequest,
  ): Promise<VerifyPasswordResponse> | Observable<VerifyPasswordResponse> | VerifyPasswordResponse;

  getChangePasswordToken(
    request: GetChangePasswordTokenRequest,
  ):
    | Promise<GetChangePasswordTokenResponse>
    | Observable<GetChangePasswordTokenResponse>
    | GetChangePasswordTokenResponse;

  changePassword(
    request: ChangePasswordRequest,
  ): Promise<ChangePasswordResponse> | Observable<ChangePasswordResponse> | ChangePasswordResponse;
}

export function PasswordServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["storePassword", "verifyPassword", "getChangePasswordToken", "changePassword"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PasswordService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PasswordService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PASSWORD_SERVICE_NAME = "PasswordService";
