// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v7.35.1
// source: auth/v1/session_pb.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { wrappers } from "protobufjs";
import { Observable } from "rxjs";

export const protobufPackage = "auth.v1";

export interface SessionInfo {
  accessToken: string;
  refreshToken: string;
  user: SessionUserInfo | undefined;
  iat: number;
  exp: number;
}

export interface SessionUserInfo {
  userId: string;
  username: string;
  email: string;
  role: string;
  isVerifed: boolean;
  createdAt: Date | undefined;
}

export interface GrantSessionRequest {
  email: string;
  password: string;
}

export interface GrantSessionResponse {
  session: SessionInfo | undefined;
}

export interface VerifySessionRequest {
  accessToken: string;
}

export interface VerifySessionResponse {
  valid: boolean;
}

export interface RevokeSessionRequest {
  accessToken: string;
  refreshToken: string;
}

export interface RevokeSessionResponse {
  revoked: boolean;
}

export interface RenewSessionRequest {
  accessToken: string;
  refreshToken: string;
}

export interface RenewSessionResponse {
  session: SessionInfo | undefined;
}

export const AUTH_V1_PACKAGE_NAME = "auth.v1";

wrappers[".google.protobuf.Timestamp"] = {
  fromObject(value: Date) {
    return { seconds: value.getTime() / 1000, nanos: (value.getTime() % 1000) * 1e6 };
  },
  toObject(message: { seconds: number; nanos: number }) {
    return new Date(message.seconds * 1000 + message.nanos / 1e6);
  },
} as any;

export interface SessionServiceClient {
  grantSession(request: GrantSessionRequest): Observable<GrantSessionResponse>;

  verifySession(request: VerifySessionRequest): Observable<VerifySessionResponse>;

  revokeSession(request: RevokeSessionRequest): Observable<RevokeSessionResponse>;

  renewSession(request: RenewSessionRequest): Observable<RenewSessionResponse>;
}

export interface SessionServiceController {
  grantSession(
    request: GrantSessionRequest,
  ): Promise<GrantSessionResponse> | Observable<GrantSessionResponse> | GrantSessionResponse;

  verifySession(
    request: VerifySessionRequest,
  ): Promise<VerifySessionResponse> | Observable<VerifySessionResponse> | VerifySessionResponse;

  revokeSession(
    request: RevokeSessionRequest,
  ): Promise<RevokeSessionResponse> | Observable<RevokeSessionResponse> | RevokeSessionResponse;

  renewSession(
    request: RenewSessionRequest,
  ): Promise<RenewSessionResponse> | Observable<RenewSessionResponse> | RenewSessionResponse;
}

export function SessionServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["grantSession", "verifySession", "revokeSession", "renewSession"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("SessionService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("SessionService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const SESSION_SERVICE_NAME = "SessionService";
